name: "Build"

on:
  workflow_call:
    inputs:
      for_deploy:
        required: true
        type: boolean
  workflow_dispatch:
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/**.yml

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-latest-arm64' || 'ubuntu-latest' }}
    strategy:
      matrix:
        arch: [amd64,arm64]
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Build Docker Image"
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          tags: amp-dockerized:latest
          outputs: type=docker,dest=/tmp/docker-image-${{ matrix.arch }}.tar
      - name: "Upload Docker Image Artifact"
        if: ${{ inputs.for_deploy == true }}
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.arch }}
          path: /tmp/docker-image-${{ matrix.arch }}.tar
