name: "Build"

on:
  workflow_call:
    inputs:
      for_deploy:
        required: true
        type: boolean
  workflow_dispatch:
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/**.yml

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64,arm64]
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build Docker Image"
        uses: docker/build-push-action@v2
        with:
          build-args: |
            "CACHE_AMP_UPGRADE=${{ inputs.for_deploy == true }}"
          context: .
          platforms: linux/${{ matrix.arch }}
          tags: amp-dockerized:latest
          outputs: type=docker,dest=/tmp/docker-image-${{ matrix.arch }}.tar
      - name: "Upload Docker Image Artifact"
        if: ${{ inputs.for_deploy == true }}
        uses: actions/upload-artifact@v2
        with:
          name: image-${{ matrix.arch }}
          path: /tmp/docker-image-${{ matrix.arch }}.tar
